eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
    hostname: localhost



microservice:
  Payment_Service:
    endpoints:
      endpoint:
        uri: http://Payment_Service/payment/doPayment
  Order_Service:
    endpoints:
      endpoint:
        uri: http://Order_Service/order/bookOrder
